### ISSUE TITLE
Multiple CSS?

### ISSUE THREAD

**Issue by yesnoj** [flyandi/mazda-custom-application-sdk#11]
Hi, i want to create a very basic app where i can choose a color, something like this https://www.jqueryscript.net/other/Tiny-HTML5-jQuery-Color-Picker-Plugin-Palette-Color-Picker.html 
so i can use the color to set the ambien light.
But if i try to import another CSS file in the require part of the app.js is not working.
Someone can help me?
Thanks :/

**Comment by flyandi** [comment]
yeah u can just import any css you want, there is no limit. Actual the app.js CSS config is an array or string and will automatically append if there is more then one.
