### ISSUE TITLE
Custom values possible?

### ISSUE THREAD

**Issue by TTigges** [flyandi/mazda-custom-application-sdk#13]
I'm working on an app that shows oil sensor readings (pressure, temperature) via an Arduino that is saving the data to "/tmp/mnt/data_persist/dev/bin/" through libusb.

The standalone speedometer app has a "speedometer.sh" where the variables vor the values are assigned like
`SPEED=`smdb-read -n vdm_vdt_current_data -e VehicleSpeed``
and it can read values from the path mentioned above.

Is it possible to get the data into a CASDK app in a similar way?

**Comment by GrayHatter** [comment]
At the very least, that's the wrong place to store that data. But I'm very interesting in how you're getting the data? The OBD2 port?

**Comment by TTigges** [comment]
Sensors connected to an Arduino. How'd you do it?

**Comment by flyandi** [comment]
There are prioritized scripts that pull that data. We started an excel sheet a while ago that lists some of the values captured through it:

https://docs.google.com/spreadsheets/d/1lkVUzhLEMglb7eFglne1iDiJ5vKMpaoxXKW-7bSZ6Ws/edit#gid=0

Scripts are in:

https://github.com/flyandi/mazda-custom-application-sdk/tree/master/src/deploy/install/casdk/scripts

**Comment by TTigges** [comment]
Perfect, thank you.
