### ISSUE TITLE
Mounting drive as readwrite during install and uninstall

### ISSUE THREAD

**Issue by alek5k** [flyandi/mazda-custom-application-sdk#2]
Hi there!

Thanks for the great tool. Are you still working on the development?
I have been able to run your install script on the runtime on my mazda3 with OS Version 56.00.240 4A N.
An issue I have noticed is that the apps do not register in my Application submenu. 

I ran the install script by SSHing in to the car over wifi, finding the usb drive (under /mnt/sdb1) and running the install. The popup message came up saying the installation was successful. See console output below:
![capture](https://cloud.githubusercontent.com/assets/20435565/16797157/875427de-4929-11e6-84a1-f1852162129b.PNG)

When reading your Wiki article I noted that in your getting started guide, you mention that the SD card has an applications folder. This seems inconsistent with the version of runtime that I have.

Additionally, I noticed in your shell scripts that you mount the filesystem as readwrite using:
mount -o rw,remount /
I would suggest that you remount the filesystem as readonly, as it seems like the car is happy to turn off the OS quickly (ie not a controlled shutdown) and if the filesystem is readwrite then this can cause corruption. This can be done (as I'm sure you know) using:
mount -o ro,remount /

Because I couldnt get it working, I ended up running the uninstall shell script as well. Cleanup seemed to go smoothly, however under /var/tmp there were still a bunch of casdk files, including a logfile. Be happy to share this if you wish. 

EDIT: So I got it to work, reading the shell script it seems that you need to place the apps folder on the navigation SD card that comes with the car. I will leave this issue open for the readonly remounting.

**Comment by alek5k** [comment]
**Web content access**

I made an app for accessing and searching youtube (happy to add this to your app repository if you like) via the embedded player. It seems opera tries to open a dialog for accepting the certificate, which doesn't come up.
![20160716_163105 - copy](https://cloud.githubusercontent.com/assets/20435565/16894952/4c2e21b8-4baa-11e6-9f89-7af5307042a6.jpg)
I'll update with more info if I find a workaround.

**Comment by quaso** [comment]
Your issue is that Opera is showing an alert message: "Server certificate expired". Which is not true. However the system time in your Mazda is 1.1.1970!
I was able to set the correct time with minor hack described here: https://github.com/quaso/mazda-enhanced-compass-routing/wiki/Setup-and-Installation-Guide#patch-clock

**Comment by flyandi** [comment]
For some reason I never got a notification for this issue. I am back on track for this project.

U still having these issues?

**Comment by alireza1351** [comment]
I need orgibak file to reunstal 56. 00. 240 pls

**Comment by alek5k** [comment]
No issues anymore, however I took my car in for a service and they did a software update. After the software update I can no longer SSH into the car and I've lost all the custom apps I had running! bummer :(

I dont know whether its worth trying a USB network card before trying a factory reset... and whether the factory reset will just move it to the failsafe version rather than the previous OS version.
