### ISSUE TITLE
Web content access

### ISSUE THREAD

**Issue by alek5k** [flyandi/mazda-custom-application-sdk#3]
Web content access

I made an app for accessing and searching youtube (happy to add this to your app repository if you like) via the embedded player. It seems opera tries to open a dialog for accepting the certificate, which doesn't come up.
![untitled](https://cloud.githubusercontent.com/assets/20435565/16894991/ff214dfe-4baa-11e6-832f-9abab9fbd56f.png)

I'll update with more info if I find a workaround.

**Comment by quaso** [comment]
Your issue is that Opera is showing an alert message: "Server certificate expired". Which is not true. However the system time in your Mazda is 1.1.1970!
I was able to set the correct time with minor hack described here: https://github.com/quaso/mazda-enhanced-compass-routing/wiki/Setup-and-Installation-Guide#patch-clock

**Comment by alek5k** [comment]
Ah, good pickup. Seemed a bit strange seeing as it was requesting http. Thanks for the link! I'll update the issue with results after testing.

**Comment by alek5k** [comment]
quaso, I just noticed that you're actively developing the mazda-enhanced-compass-routing application. Please see my other issue to do with readwrite and readonly (to avoid filesystem corruption) as it may be relevant to your project as well. Thanks!

**Comment by alek5k** [comment]
An update

Seems that changing the hardware clock time did the trick, however now I was getting a new message, shown below:
![20160717_170251](https://cloud.githubusercontent.com/assets/20435565/16899545/6269bbf8-4c4b-11e6-8fa3-b12885e4e5bc.jpg)

So this is the second time I got an error with the opengles-ui dialog. Looking in the opera directory, I found that it actually exists:
![openglesui present](https://cloud.githubusercontent.com/assets/20435565/16899546/74d8cbbc-4c4b-11e6-8fac-cbd2e2cb141a.PNG)

The issue then is that the opera browser is running in a different context to its own root directory.
Using the command 
`ps | grep opera`
I found the process id 602.

I then navigated to /proc/602 and cwd (which is a link to the current working directory) seemed to be linking to root (ie. / ).

I added a couple of symlinks so that opera running in its context would be able to find its own popup. One of these symlinks worked:

```
ln -sf /jci/opera/opengles-ui /tmp/root
ln -sf /jci/opera/opengles-ui /
```

When I ran my app again, the popup appeared and I was able to accept the dialog above (for running the local javascript files). Success! I was able to load the video:

![20160717_175258](https://cloud.githubusercontent.com/assets/20435565/16899574/483db242-4c4c-11e6-8a69-f1fca2f124f7.jpg)

Pressed play. Not working :<

![20160717_175446](https://cloud.githubusercontent.com/assets/20435565/16899579/6b73157c-4c4c-11e6-962a-a952ed14c84f.jpg)

My theory right now is that the car runs opera mini, which does not support html5 video. More info here: 
http://www.opera.com/docs/specs/productspecs/

Next step would be to confirm that the car does indeed run opera mini... and if so then can the project! (Or investigate if theres a way to get around this?)

**Comment by flyandi** [comment]
Actually it does HTML5 video but I don't think YouTube recognizes it.. you need the embed your own player with player.js or something like that.
