### ISSUE TITLE
Application doesn't show up on Infotainment System

### ISSUE THREAD

**Issue by marceljung** [flyandi/mazda-custom-application-sdk#8]
Hello together,

i have tried to install tetris on my Infotainment System like this:

1. Copied the folder content from "src/deploy/install" to a USB Stick FAT 32
2. i have pluged in the usb stick into my car and the installation was successful
3. now i copied the folder content from "apps/" to the SD card where the navigation data are also (like this: "sd_nav/app.tetris")
4. back to my car i pluged in the sd card and restarted the Infotainment System

What I have done wrong, because no apps are displayed ?

Wrong path on the SD card ?
Maybe it is not the right order ?
I dont know whats wrong.

**Comment by flyandi** [comment]
Did u ever solve it?
